### PR TITLE
nuevo cambio readme.md

### PR DESCRIPTION
**Pull request by rivera06**
nuevo cambio en archivo

---
This change is [Reviewable](https://reviewable.io/reviews/irvinsanchez14/api-jws/6)

### CODE REVIEW

**Review by IrvinSanchez14 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/irvinsanchez14/api-jws/6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @IrvinSanchez14 and @rivera06)

___
*[README.md, line 6 at r1](https://reviewable.io/reviews/irvinsanchez14/api-jws/6#-LcdJEJsArecKZWI30VB:-LcdJEJt3EHK4WHnJ38e:bs9yhvq) ([raw file](https://github.com/irvinsanchez14/api-jws/blob/b7a5e543173fc72210c77d585a601d2f10a4b4d1/README.md#L6)):*
> ```Markdown
> irvin puto
> reputo el q lo lea 
> cambio en readme.md
> ```

deja espacio en blanco abajo

**Review by rivera06 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/irvinsanchez14/api-jws/6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @IrvinSanchez14)

___
*[README.md, line 6 at r1](https://reviewable.io/reviews/irvinsanchez14/api-jws/6#-LcdJEJsArecKZWI30VB:-LcdKiknBMULTURs48gQ:b5qgivg) ([raw file](https://github.com/irvinsanchez14/api-jws/blob/b7a5e543173fc72210c77d585a601d2f10a4b4d1/README.md#L6)):*
<details><summary><i>Previously, IrvinSanchez14 (Irvin Sanchez) wrote…</i></summary><blockquote>

deja espacio en blanco abajo
</blockquote></details>

Done.
ya esta gran cerote quisquilloso

**Review by IrvinSanchez14 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/irvinsanchez14/api-jws/6#-:-LcdKz1nBxyTd94FsH9a:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by IrvinSanchez14 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/irvinsanchez14/api-jws/6#-:-LcdLCOpCnn--htmQjZK:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by IrvinSanchez14 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/irvinsanchez14/api-jws/6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
