### PR TITLE
Mi primer commit Raul

### PR DESCRIPTION
**Pull request by raulrafael**
kk

---
This change is [Reviewable](https://reviewable.io/reviews/irvinsanchez14/api-jws/3)

### CODE REVIEW

**Review by IrvinSanchez14 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/irvinsanchez14/api-jws/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @raulrafael)

___
*[README.md, line 5 at r1](https://reviewable.io/reviews/irvinsanchez14/api-jws/3#-LcdAwlvBTuAoAuyrHbW:-LcdAwlvBTuAoAuyrHbX:b-oibjyu) ([raw file](https://github.com/irvinsanchez14/api-jws/blob/af6a7a9356c9b031fb5530213bd6a4ff6671f653/README.md#L5)):*
> ```Markdown
> branch IRVIN donde
> irvin puto
> reputo el q lo lea 
> ```

quitar linea de espacio blanco

**Review by raulrafael — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/irvinsanchez14/api-jws/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @IrvinSanchez14)

___
*[README.md, line 5 at r1](https://reviewable.io/reviews/irvinsanchez14/api-jws/3#-LcdAwlvBTuAoAuyrHbW:-LcdBapB1p-QWc01spge:b-896fix) ([raw file](https://github.com/irvinsanchez14/api-jws/blob/af6a7a9356c9b031fb5530213bd6a4ff6671f653/README.md#L5)):*
<details><summary><i>Previously, IrvinSanchez14 (Irvin Sanchez) wrote…</i></summary><blockquote>

quitar linea de espacio blanco
</blockquote></details>

Done.

**Review by IrvinSanchez14 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/irvinsanchez14/api-jws/3#-:-LcdBl1h6maHgM3kES9z:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @IrvinSanchez14)

**Review by IrvinSanchez14 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/irvinsanchez14/api-jws/3)* status: all files reviewed, 1 unresolved discussion (waiting on @IrvinSanchez14)

**Review by IrvinSanchez14 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/irvinsanchez14/api-jws/3#-:-LcdBtrm4mmRvrhfZesP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
